Repository UBC-MDS/Pythoshop, pull requests merged in 2024-02, with the labels that each got.

#107 fix: updated the version of the toml file
  pyproject.toml
Labels: documentation

#108 105 fix resize image function and test corresponding to the changes made
  src/pythoshop/resize_image.py
  tests/test_resize_image.py
Labels: bug, documentation

#111 104 fix the adjust brightness function and the tests
  src/pythoshop/adjust_brightness.py
  tests/test_adjust_brightness.py
  tests/test_img_1_brightness_changed.png
Labels: bug, enhancement

#110 added changed function and tests for apply filter
  src/pythoshop/apply_filter.py
  tests/test_apply_filter.py
Labels: bug, individual-work

#117 docs: Update README.md with input "image" instead of "image_path"
  README.md
Labels: documentation

#118 97 update badges
  README.md
Labels: documentation, enhancement

#123 fix: Added code coverage token to ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: bug

#128 fix: Deleted new codecov action from ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: bug

#129 fix: Fixed examples and other functions so that we don't need to save…
  docs/example.ipynb
Labels: enhancement, individual-work
