Repository UBC-MDS/Pythoshop, pull requests merged in 2024-01, with the labels that each got.

#24 creating apply filter docstrings
  src/pythoshop/pythoshop.py
Labels: individual-work

#28 docs: Updated CHANGELOG.md for milestone 1
  CHANGELOG.md
Labels: documentation

#30 feat: cropping functionality created
  poetry.lock
  pyproject.toml
  src/pythoshop/pythoshop.py
  tests/mds_logo.png
  tests/mds_logo.png_adj_img.png
  tests/test_img_1.png
  tests/test_pythoshop.py
Labels: group-work

#40 added apply filter function body
  src/pythoshop/apply_filter.py
  tests/test_apply_filter.py
Labels: individual-work

#47 modified test functions
  src/pythoshop/apply_filter.py
  tests/test_apply_filter.py
Labels: individual-work

#46 added function body and tests - adjust_brightness
  docs/example.ipynb
  poetry.lock
  pyproject.toml
  src/pythoshop/adjust_brightness.py
  tests/test_adjust_brightness.py
  tests/test_pythoshop.py
Labels: individual-work

#43 42 test resize image function
  docs/example.ipynb
  poetry.lock
  src/pythoshop/adjust_brightness.py
  src/pythoshop/apply_filter.py
  src/pythoshop/resize_image.py
  tests/mds_logo.png_adj_img.png
  tests/test_adjust_brightness.py
  tests/test_apply_filter.py
  tests/test_pythoshop.py
  tests/test_resize_image.py
Labels: individual-work

#50 docs: updated README.md file
  README.md
Labels: documentation

#48 Transform image test and function
  poetry.lock
  src/pythoshop/transform_image.py
  tests/test_transform_image.py
  tests/test_transform_image2.py
Labels: individual-work

#54 53 fix files lost in previous merge
  docs/example.ipynb
  src/pythoshop/adjust_brightness.py
  src/pythoshop/apply_filter.py
  tests/test_adjust_brightness.py
  tests/test_apply_filter.py
Labels: bug

#56 docs: updated README.md with conda and poetry instrunctions
  README.md
  docs/index.html
Labels: documentation

#57 44 update the example file
  docs/example.ipynb
  src/pythoshop/pythoshop.py
  tests/test_pythoshop.py
  tests/test_transform_image2.py
Labels: group-work

#59 55 update readmemd file with instructions on installing conda and poetry
  README.md
Labels: documentation, discussion

#60 58 fix transform function bug
  docs/example.ipynb
  src/pythoshop/transform_image.py
  tests/test_transform_image.py
Labels: bug

#65 Added logo
  docs/conf.py
  docs/img/pythoshop-logo.png
  docs/index.md
Labels: individual-work

#69 added default project configuration file
  .readthedocs.yaml
Labels: documentation, individual-work

#70 changed readthedocs file
  .readthedocs.yaml
Labels: individual-work

#71 changed image path
  README.md
Labels: documentation

#74 68 create readthedocs documentation
  docs/example.ipynb
  docs/index.md
Labels: bug, group-work

#75 changed filter
  src/pythoshop/apply_filter.py
Labels: bug

#77 added matplotlib aggregation functions
  src/pythoshop/adjust_brightness.py
  src/pythoshop/resize_image.py
  src/pythoshop/transform_image.py
Labels: bug

#78 Update README.md with button
  README.md
Labels: documentation

#93 fixed image path to go along with new image path encryption
  tests/test_adjust_brightness.py
  tests/test_img_1.png_brightness_changed.png
  tests/test_img_1.png_filter_img.png
  tests/test_img_1_brightness_changed.png
Labels: bug, group-work
